Replace absolute path with a relative one in the model saving/loading procedure
salesforce/Merlion pull request #63
Opened 2022-01-20 10:52 UTC by isenilov

Currently, the saving method records an absolute path to a pickled model in the configuration which is evident for example in the output of cell 13 [here].(https://github.com/salesforce/Merlion/blob/7d968afbf185a16bc9947fdc4c23275d4e876e9a/examples/anomaly/1_AnomalyFeatures.ipynb).
It creates a problem when one needs to move the dir with the config and the model around and load the model from the new location.

The proposed change attempts to solve it by saving the relative path to a model which is, in the current implementation of storing the model file along with the configuration in the same dir, basically the name of the model pickle file.

2022-01-20 20:43 UTC, aadyotb requested changes
Thanks for the change! The existing method (with the absolute path) is a holdover from an older version of the codebase. Given that the relative model path just `self.filename` now, could you actually remove the step where we set `config_dict["model_path"] = model_path` altogether?

Additionally, could you re-run all the tutorials on your machine, to make sure that they no longer include the abspath in any configs that get printed out?

2022-01-21 08:52 UTC, isenilov commented
> Thanks for the change! The existing method (with the absolute path) is a holdover from an older version of the codebase. Given that the relative model path is just `self.filename` now, could you actually remove the step where we set `config_dict["model_path"] = model_path` altogether?

Yeah, I was thinking about that but was not sure as the `save` method used instance's property `self.filename` but the `load` method is Class method and uses `cls.filename`. But as one is required to run the load method from the particular class which should match the model to be loaded, it should work fine.

> Additionally, could you re-run all the tutorials on your machine, to make sure that they no longer include the abspath in any configs that get printed out (like the one you linked in the main PR comment)?

Done. There is my username in a couple of cell outputs now (not related to the `model_path`) :) Hope that is fine, otherwise, feel free to amend.

2022-01-25 00:55 UTC, aadyotb approved these changes

2022-01-25 00:55 UTC, merged

2022-01-25 00:55 UTC, aadyotb commented
Thanks! Merged to main :)